/*
 * stubs.c
 *
 *  Created on: 28-Aug-2014
 *      Author: nikhil
 */

/**
 * @Warning DO NOT EDIT THIS FILE!
 * This file contain stubs to get rid of compilation errors
 */

#include <stdio.h>

#include "ch.h"
#include "hal.h"

#include "stubs.h"
/**
 * @Warning DO NOT EDIT THIS FUNCTION!
 */
void _exit(int status){
   (void) status;
   chSysHalt();

   while(TRUE){}
}
/**
 * @Warning DO NOT EDIT THIS FUNCTION!
 */
pid_t _getpid(void){
   return 1;
}
/**
 * @Warning DO NOT EDIT THIS FUNCTION!
 */
void _kill(pid_t id){
   (void) id;
}

/* guard variables *//**
 * @Warning DO NOT EDIT THIS FUNCTION!
 */
int __cxa_guard_acquire(__guard *g) {return !*(char *)(g);};
void __cxa_guard_release (__guard *g) {*(char *)g = 1;};
void __cxa_guard_abort (__guard * g __attribute__((unused))) {};
